language: elixir
elixir:
  - 1.2.6
  - 1.3.1
  - 1.5.2
otp_release:
  - 18.2
  - 19.0
  - 20.1
before_install:
  - sudo apt-get update
  - sudo apt-get install imagemagick graphicsmagick
env:
  - MIX_ENV=test
  - MIX_ENV=graphicsmagick_test
